<a href="https://colab.research.google.com/github/useDeep/learn_pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00_pytorch_fundamentals

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


### Introduction to tensors

### Creating tensors

In [2]:
# scalar
scalar= torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# vector

vector= torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX= torch.tensor([[7, 8], [1, 5]])
MATRIX

tensor([[7, 8],
        [1, 5]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
#TENSOR
TENSOR= torch.tensor([[[1, 2, 3],
                       [5, 8, 6],
                       [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 8, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [14]:
random_tensor= torch.rand(3, 4)
random_tensor

tensor([[0.7801, 0.1754, 0.9946, 0.0261],
        [0.1850, 0.1043, 0.2687, 0.4945],
        [0.7575, 0.4512, 0.1006, 0.8676]])

In [15]:
random_tensor.ndim

2

In [16]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(size= (224, 224, 3))   # height, width, colour channels
random_image_size_tensor

tensor([[[0.9070, 0.9840, 0.7361],
         [0.9742, 0.7986, 0.4445],
         [0.4738, 0.2479, 0.3015],
         ...,
         [0.4807, 0.1973, 0.4222],
         [0.0430, 0.3170, 0.7519],
         [0.0683, 0.7350, 0.4770]],

        [[0.5465, 0.1877, 0.1258],
         [0.1021, 0.3706, 0.0605],
         [0.5905, 0.2966, 0.1761],
         ...,
         [0.0271, 0.4417, 0.1430],
         [0.7884, 0.9502, 0.1564],
         [0.9299, 0.1738, 0.0600]],

        [[0.2284, 0.2720, 0.4402],
         [0.5346, 0.8333, 0.4368],
         [0.2450, 0.3193, 0.7040],
         ...,
         [0.1922, 0.0505, 0.0365],
         [0.9712, 0.8954, 0.6230],
         [0.5095, 0.0193, 0.4352]],

        ...,

        [[0.7431, 0.8995, 0.3552],
         [0.9655, 0.3913, 0.3974],
         [0.4373, 0.4817, 0.9600],
         ...,
         [0.1973, 0.2181, 0.1360],
         [0.8139, 0.8832, 0.9080],
         [0.3512, 0.3022, 0.7616]],

        [[0.0114, 0.9374, 0.3867],
         [0.7605, 0.6903, 0.2836],
         [0.

In [17]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

### zeroes and ones

In [18]:
zeroes= torch.zeros(3, 4)
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeroes * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones= torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### creating a range of tensors and tensors-like

In [22]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
one_to_k= torch.arange(start=0, end= 1000, step=50)
one_to_k

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [24]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [25]:
# creating tensor like
ten_zeroes= torch.zeros_like(input= one_to_k)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [26]:
# Float 32 tensor
float_32= torch.tensor([1.0, 2.0, 3.0],
                       dtype= None,           # what datatype is the tensor (ex: float32, float16)
                       device= 'cpu',         # what device is your tensor on
                       requires_grad= True)   # whether or not to track gradients with tensors operations
float_32

tensor([1., 2., 3.], requires_grad=True)

In [27]:
float_32.dtype

torch.float32

In [28]:
float_16= float_32.type(torch.float16)     # convert float32 tensor to float16
float_16.dtype

torch.float16

In [29]:
float_16 * float_32

tensor([1., 4., 9.], grad_fn=<MulBackward0>)

In [30]:
# Create a tensor
x= torch.rand(3, 4, dtype=torch.float16)
x

tensor([[0.4521, 0.6636, 0.1372, 0.2949],
        [0.1870, 0.8433, 0.3208, 0.0591],
        [0.2290, 0.0459, 0.4536, 0.9014]], dtype=torch.float16)

### Tensor attributes

In [31]:
print(f"Datatype of tensor: {x.dtype}")
print(f"Shape of tensor: {x.shape}")
print(f"Size of tensor: {x.size}")    # function not attribute
print(f"Size of tensor: {x.size()}")

Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Size of tensor: <built-in method size of Tensor object at 0x78e66e1d7980>
Size of tensor: torch.Size([3, 4])


In [32]:
print(f"Device tensor running on: {x.device}")

Device tensor running on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include
- Addition
- Subtraction
- Multiplication (element wise)
- Division
- Matrix multiplication

In [33]:
# Create a tensor
tensor= torch.tensor([1, 2, 3])
tensor + 5

tensor([6, 7, 8])

In [34]:
tensor * 5

tensor([ 5, 10, 15])

In [35]:
# pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [36]:
torch.subtract(tensor, 1)

tensor([0, 1, 2])

### Matrix multiplication



In [39]:
# Element wise multiplication
print(tensor, " * ", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3])  *  tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [40]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
tensor_a= torch.tensor([[1, 2],
                        [2, 3],
                        [5, 6]])
tensor_b= torch.tensor([[3, 4],
                        [5, 7],
                        [5, 9]])

torch.mm(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [43]:
tensor_b.T    # .T  -> transpose

tensor([[3, 5, 5],
        [4, 7, 9]])

In [44]:
torch.matmul(tensor_a, tensor_b.T)

tensor([[11, 19, 23],
        [18, 31, 37],
        [39, 67, 79]])

### Finding min, mean, max, sum, etc (tensor aggregation)

In [47]:
# Creating a tensor
x= torch.arange(0, 100, 1)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [59]:
torch.min(x), torch.max(x) , x.min()

(tensor(0), tensor(99), tensor(0))

In [58]:
torch.mean(x, dtype=torch.float16), x.mean(dtype=torch.float16)

(tensor(49.5000, dtype=torch.float16), tensor(49.5000, dtype=torch.float16))

In [60]:
torch.sum(x), x.sum()

(tensor(4950), tensor(4950))

### Finding the positional min and max

In [64]:
x.argmin(), x.argmax(), torch.argmin(x)

(tensor(0), tensor(99), tensor(0))

In [67]:
x.argsort()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Reshaping, stacking, squeezing and unsqueezing

- Reshaping - reshapes an input tensor to defined shape
- View - Return the view of an input tensor of certain shape but keep the same memory as the original tensor
- Staking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - removes all 1 dimensions from a tensor
- Unsqueeze - add a 1 dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted in a certain way

In [89]:
x= torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [90]:
x_reshaped= x.reshape(3, 3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [91]:
# Changing view
z= x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [92]:
# Changing z changes x (because the veiw of a tensor shares the same memory as the original tensor)
z[:, 0]= 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [95]:
# Stack tensors on top of each other
x_stacked= torch.stack([x, x, x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [96]:
# Stack tensors side by side
x_stacked= torch.stack([x, x, x], dim= 1)
x_stacked

tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [123]:
# squeeze
x= torch.zeros(2, 1, 2, 1, 2)     # Squeezing tensors removes the single dimenstions
x, x.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [124]:
y= x.squeeze()    # or y= torch.squeeze(x)
y, y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [125]:
# unsqueeze() - adds a single dimensions to a target tensor at a specific dimension
y= y.unsqueeze(dim= 0)
y, y.size()



(tensor([[[[0., 0.],
           [0., 0.]],
 
          [[0., 0.],
           [0., 0.]]]]),
 torch.Size([1, 2, 2, 2]))

In [130]:
# permute
x= torch.randn(3, 5, 2)      # Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution).

x.size()

torch.Size([3, 5, 2])

In [133]:
y= torch.permute(x, (2, 0, 1))    # permute returns a view, so if the returned tensor is changed, the original one changes
y.size()

torch.Size([2, 3, 5])

In [137]:
y[0][0][0]= 5

In [138]:
y, x

(tensor([[[ 5.0000, -0.0108,  0.5638, -0.1007, -1.1041],
          [ 0.8830, -0.0207,  0.0486,  1.6030,  0.6300],
          [ 0.3799, -0.9619, -1.7072, -0.6983,  0.9832]],
 
         [[ 1.4362, -0.1514, -1.2762, -0.6562, -0.0495],
          [ 1.2768, -1.0825, -0.3473, -0.1936, -0.9065],
          [-0.7384,  0.2274,  2.3088,  1.3667, -0.2812]]]),
 tensor([[[ 5.0000,  1.4362],
          [-0.0108, -0.1514],
          [ 0.5638, -1.2762],
          [-0.1007, -0.6562],
          [-1.1041, -0.0495]],
 
         [[ 0.8830,  1.2768],
          [-0.0207, -1.0825],
          [ 0.0486, -0.3473],
          [ 1.6030, -0.1936],
          [ 0.6300, -0.9065]],
 
         [[ 0.3799, -0.7384],
          [-0.9619,  0.2274],
          [-1.7072,  2.3088],
          [-0.6983,  1.3667],
          [ 0.9832, -0.2812]]]))

## Pytorch and Numpy

- Data in numpy to pytorch tensor -> `torch.from_numpy(ndarray)`
- Pytorch tensor -> `torch.Tensor.numpy()`

In [151]:
# Numpy array to tensor

array= np.arange(1, 10)
tensor= torch.from_numpy(array)   # when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of int64, unless specified using tensor= torch.from_numpy(array).type(int32)

array, tensor, tensor.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.int64)

In [152]:
array[0]= 50
array, tensor

(array([50,  2,  3,  4,  5,  6,  7,  8,  9]),
 tensor([50,  2,  3,  4,  5,  6,  7,  8,  9]))

In [153]:
array= array+ 1
array, tensor

(array([51,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([50,  2,  3,  4,  5,  6,  7,  8,  9]))

In [154]:
# Tensor to numpy array

tensor= torch.ones(5)
np_array= tensor.numpy()

tensor, np_array

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [155]:
tensor= tensor + 1
tensor, np_array

(tensor([2., 2., 2., 2., 2.]), array([1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility

- To reduce the randomnesss in neural networks and pytorch comes with a concept of a random seed


In [159]:
a= torch.rand(3, 4)
b= torch.rand(3, 4)

print(a)
print(b)
print(a== b)

tensor([[0.2756, 0.2734, 0.6039, 0.2516],
        [0.2778, 0.1766, 0.9149, 0.9105],
        [0.2639, 0.4295, 0.3842, 0.5658]])
tensor([[0.5125, 0.9554, 0.1299, 0.0435],
        [0.7777, 0.4477, 0.8085, 0.1820],
        [0.6566, 0.6708, 0.2290, 0.7496]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [162]:
RANDOM_SEED= 75
torch.manual_seed(RANDOM_SEED)

random_tensor_a= torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_b= torch.rand(3, 4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a== random_tensor_b)

tensor([[0.6487, 0.3296, 0.8868, 0.6205],
        [0.3563, 0.6020, 0.9925, 0.3728],
        [0.0012, 0.4957, 0.3346, 0.3869]])
tensor([[0.6487, 0.3296, 0.8868, 0.6205],
        [0.3563, 0.6020, 0.9925, 0.3728],
        [0.0012, 0.4957, 0.3346, 0.3869]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running pytorch objects on the GPUs

In [164]:
torch.cuda.is_available()

False

In [166]:
# Setup device agnostic code
device= "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [167]:
# count number of devices
torch.cuda.device_count()

0

In [168]:
# tensor on cpu (default)
tensor= torch.tensor([1, 2, 3], device= "cpu")
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [171]:
# Move tensor to GPU (if available)

device= "cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu= tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

### numpy works only on cpu. Moving tensors back to cpu

In [172]:
# if tensor is on gpu, can't transform it to numpy
tensor_back_on_cpu= tensor_on_gpu.cpu().numpy()