<a href="https://colab.research.google.com/github/useDeep/learn_pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00_pytorch_fundamentals

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


### Introduction to tensors

### Creating tensors

In [ ]:
# scalar
scalar= torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# vector

vector= torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX= torch.tensor([[7, 8], [1, 5]])
MATRIX

tensor([[7, 8],
        [1, 5]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR= torch.tensor([[[1, 2, 3],
                       [5, 8, 6],
                       [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [5, 8, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [ ]:
random_tensor= torch.rand(3, 4)
random_tensor

tensor([[0.1022, 0.3983, 0.0900, 0.2521],
        [0.2553, 0.6834, 0.6554, 0.5522],
        [0.6505, 0.0256, 0.2427, 0.9725]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor= torch.rand(size= (224, 224, 3))   # height, width, colour channels
random_image_size_tensor

tensor([[[0.7548, 0.5744, 0.6998],
         [0.3287, 0.2657, 0.5938],
         [0.1307, 0.3288, 0.2852],
         ...,
         [0.4489, 0.0068, 0.6118],
         [0.7082, 0.1894, 0.1759],
         [0.3345, 0.5227, 0.9116]],

        [[0.8598, 0.8065, 0.2237],
         [0.6409, 0.0460, 0.4905],
         [0.4129, 0.9968, 0.6906],
         ...,
         [0.9276, 0.2671, 0.0967],
         [0.4247, 0.0103, 0.7000],
         [0.5579, 0.9974, 0.0019]],

        [[0.3138, 0.1849, 0.8250],
         [0.3191, 0.9073, 0.9176],
         [0.5621, 0.5283, 0.7249],
         ...,
         [0.6929, 0.9697, 0.4431],
         [0.5102, 0.2877, 0.4746],
         [0.6804, 0.6603, 0.2629]],

        ...,

        [[0.4652, 0.0446, 0.0632],
         [0.9233, 0.4324, 0.5590],
         [0.6558, 0.2391, 0.2154],
         ...,
         [0.3140, 0.7726, 0.1853],
         [0.4928, 0.1242, 0.1668],
         [0.6976, 0.9573, 0.7780]],

        [[0.2250, 0.0570, 0.5018],
         [0.4351, 0.0594, 0.6913],
         [0.

In [ ]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

### zeroes and ones

In [ ]:
zeroes= torch.zeros(3, 4)
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeroes * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones= torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### creating a range of tensors and tensors-like

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_k= torch.arange(start=0, end= 1000, step=50)
one_to_k

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [ ]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [ ]:
# creating tensor like
ten_zeroes= torch.zeros_like(input= one_to_k)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [ ]:
# Float 32 tensor
float_32= torch.tensor([1.0, 2.0, 3.0],
                       dtype= None,           # what datatype is the tensor (ex: float32, float16)
                       device= 'cpu',         # what device is your tensor on
                       requires_grad= True)   # whether or not to track gradients with tensors operations
float_32

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
float_32.dtype

torch.float32

In [ ]:
float_16= float_32.type(torch.float16)     # convert float32 tensor to float16
float_16.dtype

torch.float16

In [ ]:
float_16 * float_32

tensor([1., 4., 9.], grad_fn=<MulBackward0>)

In [ ]:
# Create a tensor
x= torch.rand(3, 4, dtype=torch.float16)
x

tensor([[0.0190, 0.2036, 0.6738, 0.4824],
        [0.5117, 0.2480, 0.6582, 0.1997],
        [0.3677, 0.7876, 0.7651, 0.4731]], dtype=torch.float16)

### Tensor attributes

In [ ]:
print(f"Datatype of tensor: {x.dtype}")
print(f"Shape of tensor: {x.shape}")
print(f"Size of tensor: {x.size}")    # function not attribute
print(f"Size of tensor: {x.size()}")

Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Size of tensor: <built-in method size of Tensor object at 0x7b0c68b4bc50>
Size of tensor: torch.Size([3, 4])


In [ ]:
print(f"Device tensor running on: {x.device}")

Device tensor running on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include
- Addition
- Subtraction
- Multiplication (element wise)
- Division
- Matrix multiplication

In [ ]:
# Create a tensor
tensor= torch.tensor([1, 2, 3])
tensor + 5

tensor([6, 7, 8])

In [ ]:
tensor * 5

tensor([ 5, 10, 15])

In [ ]:
# pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.subtract(tensor, 1)

tensor([0, 1, 2])